name: 'actions-otrs'
description: 'Action to scan comments for OTRS Ticket URLs and notify those tickets'
author: 'tangro'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  label:
    description: 'Add this label to the issue'
    required: false
    default: 'Ticket'

runs:
  using: 'node16'
  main: 'dist/index.js'
